CUDA_VISIBLE_DEVICES=1 python main_block_ap.py \
--model  /home/nku509/models/llama/llama3/llama3.1_8b_hf \
--output_dir ./output/block_ap_log/Llama-3-8b-w2g128 \
--net Llama-3 \
--calib_dataset c4 \
--wbits 2 \
--group_size 128 \
--quant_lr 8e-5 \
--val_size 2 \
--train_size 1024 \
--eval_ppl \
--real_quant \
--epoch 2 \
--save_quant_dir ./output/block_ap_models/Llama-3-8b-w2g128